/**
 * Base class for all errors generated by the script
 */
export default class TwilioError extends Error {
  constructor(message: string) {
    super(message);

    Object.setPrototypeOf(this, TwilioError.prototype);
  }
}
